### ISSUE TITLE
Metashaker not working? 

### ISSUE THREAD

**Issue by carlolaurenzi** [Cycling74/percolate#39] opened 2020-10-08 23:48 UTC
Hi, I am trying metashaker, but I can't have any sound out of it.
I am on max 8.1.6
Maybe the object must be recompiled for max 64bits? 
I don't have any warning anyway.. 

Thanks for any help!

**Comment by isabelgk** [comment] 2020-12-11 20:24
Closing as duplicate of #40

**Closed by isabelgk** 2020-12-11 20:24 UTC
